apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-svc-prometheus-svc
  namespace: argocd
spec:
  destination:
    namespace: dev-platform-team-prometheus-svc-prometheus-svc
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: kustomization.yaml
      include: '*.yaml'
      recurse: true
    path: ./prometheus
    repoURL: https://github.com/microsoft/kalypso-svc-gitops
    targetRevision: dev
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
