apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: functional-test
  namespace: flux-system
spec:
  interval: 2m30s
  ref:
    branch: dev
  secretRef:
    name: repo-secret
  url: https://github.com/microsoft/kalypso-app-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: functional-test
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./functional-test
  prune: true
  sourceRef:
    kind: GitRepository
    name: functional-test
  targetNamespace: dev-kaizen-app-team-functional-test
